version: '2'
services:
    nginx:
        image: docker.finogeeks.club/monitor/nginx
        volumes:
          - ./nginx.conf:/nginx/conf/nginx.conf
        ports:
          - 10080:80
          - 10443:443
          - 9092:9092
